### ISSUE TITLE
Lisää rakennuksille kenttä asukasmäärälle

### ISSUE THREAD

**Issue by LKajan** [punosmobile/jkr-core#10]

**Comment by Rikuoja** [comment]
Mihin tietoa tarvitaan?

**Comment by TiiaY** [comment]
lisätieto

**Comment by Rikuoja** [comment]
Jos tämä liittyy lietteenkäsittelyyn, voidaan lisätä myöhemmässä vaiheessa.

**Comment by ltalve** [comment]
Jos vanhimmalla asukkaalla on turvakielto, asukkaan tietoja ei näy. DVV:ssä tällöin tyhjä rivi asukastiedon osalta, joka pitäisi ehkä tuoda “tyhjänä asukkaana”.
