### ISSUE TITLE
Kompostorien ja päätösten päivityksestä varoitus

### ISSUE THREAD

**Issue by ismogis** [punosmobile/jkr-core#115]
Kompostorien ja päätösten päivitys kohteiden päivityksen yhteydessä aiheuttaa testeissä seuraavat virheilmoitukset:

test_data_import.py::test_update_dvv_kohteet
  C:\dev\jkr-lahti\jkr-core\jkrimporter\providers\db\services\kohde.py:992: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
    Viranomaispaatokset.rakennus_id.in_(rakennus_ids),

test_data_import.py::test_update_dvv_kohteet
  C:\dev\jkr-lahti\jkr-core\jkrimporter\providers\db\services\kohde.py:1010: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
    Kompostori.id.in_(kompostori_ids),

test_data_import.py::test_update_dvv_kohteet
  C:\dev\jkr-lahti\jkr-core\jkrimporter\providers\db\services\kohde.py:1020: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
    Kompostori.id.in_(kompostori_ids),

test_data_import.py::test_update_dvv_kohteet
  C:\dev\jkr-lahti\jkr-core\jkrimporter\providers\db\services\kohde.py:1029: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
    .filter(Kompostori.id.in_(kompostori_id_by_date))

test_data_import.py::test_update_dvv_kohteet
  C:\dev\jkr-lahti\jkr-core\jkrimporter\providers\db\services\kohde.py:1034: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
    KohteenOsapuolet.osapuoli_id.in_(kompostori_osapuoli_ids),

test_data_import.py::test_update_dvv_kohteet
  C:\dev\jkr-lahti\jkr-core\jkrimporter\providers\db\services\kohde.py:1042: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
    KompostorinKohteet.kompostori_id.in_(kompostori_id_by_date)

Nämä ovat todennäköisesti seurausta PR:stä https://github.com/GispoCoding/jkr-core/pull/114 .

**Comment by AnniinaMet** [comment]
Todennäköisesti edelleen ajnakohtainan, mutta vaatii vielä uudelleen mietintää

**Comment by tero-punos** [comment]
Siirretty Jiraan avoimena
