### ISSUE TITLE
Muokkaa importskriptit lukemaan yhteysparametrit ympäristömuuttujista tai argumenteista

### ISSUE THREAD

**Issue by LKajan** [punosmobile/jkr-core#12]
Tällä hetkellä, kun tausta-aineistojen import halutaan ajaa testi tai tuotantoympäristöön tulee itse importskritpiä muuttaa. Tällöin git näkee tiedoston muuttuneen ja tiedoston palauttaminen/muokkaaminen takaisin on "vaivalloista"/ärsyttävää. Lisäksi yhteysparametrit voivat vuotaa julkiseen gitrepoon.

Tietokannan yhteysparametrit voitaisiin lukea joko .env tiedostoista (vaikka `.env.test`, `.env.prod`), jolloin importille voisi antaa argumenttina kohdeympäristön, jonka perusteella se lukee oikean .env-tiedoston.
Toinen vaihtoehto olisi antaa kaikki parametrit argumentteina skriptille.

**Comment by AnniinaMet** [comment]
Envitiedostot ovat käytössä, joten ongelma lienee korjattu niillä. Envitiedostojen tietoturvaa lienee tarpeen tarkastella tarkemmin, mutta itse issue on vanhentunut ja oletettavasti Tamperetta varten luotu.
