### ISSUE TITLE
Virhe yksittäistalojen kohteiden voimassaolon tarkistuksessa

### ISSUE THREAD

**Issue by ismogis** [punosmobile/jkr-core#123]
Tiedoston kohde.py funktiossa get_or_create_single_asunto_kohteet on sama bugi, joka on korjattu toisen funktion osalta PR:ssä https://github.com/GispoCoding/jkr-core/pull/122. Funktiota käytetään vain yksittäistalokohteiden luonnissa ja päivityksessä. Tätä kirjatessa ei ole tiedossa tapausta, jossa yksittäistalokohteen pitäisi olla voimassa, kun kohteita päivitetään: bugilla ei siis ole käytännön merkitystä.

**Comment by AnniinaMet** [comment]
Tämä on mahdollisesti edelleen ajankohtainen ongelma
