### ISSUE TITLE
Poista yli 5v vanhat kuljetustiedot ja asiakkuudet

### ISSUE THREAD

**Issue by LKajan** [punosmobile/jkr-core#25]
GDPR:n takia pitää pystyä säilömään tietoja, mutta myös poistamaan. Suunniteltava miten toteutus tehdään ja miten tiedot arkistoidaan.

**Comment by ltalve** [comment]
Jätelain §143 mukaan 5 vuoden ajan säilytettävä kaikki kuljetustiedot, tämän jälkeen poistettava.

**Comment by Rikuoja** [comment]
Onko nyt päätetty, että 2021 aiempaa dataa ei viedä kuljetuksista? Tällainen ajatus esitettiin käyttäjätarinoiden yhteydessä.

**Comment by ltalve** [comment]
Tästä on tehty Tampereella toteutus: https://github.com/GispoCoding/tampere-jkr/issues/143

**Comment by AnniinaMet** [comment]
Tämä tulee ajankohtaiseksi, kun tieto vanhenee.

**Comment by tero-punos** [comment]
Siirretty Jiraan taskina
