### ISSUE TITLE
Muut Tampereen koodiin tehdyt lisäykset coreen

### ISSUE THREAD

**Issue by Rikuoja** [punosmobile/jkr-core#30]
Käytävä läpi ja lisättävä coreen Tampereen koodiin tehdyt ominaisuudet (velvoitteet jne.), useamman urakoitsijan tuki, kuljetustietojen tuonnin korjaukset.

**Comment by Rikuoja** [comment]
Lisättävä yleispätevät velvoitteet.

Lyhyen tutustumisen perusteella näyttää sillä, että tietokantamalli ja funktiot coressa on ajan tasalla, mutta coresta puuttuvat itse sekajäte-, biojäte- jne. velvoitemallit.

**Comment by AnniinaMet** [comment]
ei varmaankaan enää ajankohtainen
