### ISSUE TITLE
Muuta tyhjennysvälin kenttä numericiksi

### ISSUE THREAD

**Issue by LKajan** [punosmobile/jkr-core#36]
Nyt tyhjennnysvälin kenttä on tietokannassa kokonaisuluku, joka kertoo kuinka monta kertaa tyhjennys tehdään viikossa.
Aineistossa on kuitenkin sopimuksia, joissa tyhjennys tehdään monta kertaa vikkossa. Nämä ilmoitetaan esim. 0,5 (2 krt viikossa) tai 0,25 (4 krt viikossa). Nämä pyöristyvät nyt kokonaisluvuksi, jolloin tyhjennysväli tietokannassa on väärin.

Muutetaan kenttä numeric(4,2) muotoiseksi:
 - pgmodeler mallissa
 - uusi migraatio

Sopimustiedot mahdollisesti ajettava uudelleen, jotta virheelliset tyhjennysvälit tietokannassa korjaantuvat.

**Comment by AnniinaMet** [comment]
Kuljetustiedoissa tyhjennysväli ja tiheys tulevat erillisinä tietoina, kumpikin kokonaislukina. Tämä saattaa olla Tampereen ongelma
