### ISSUE TITLE
Lisää keräysvälineelle aikaväli koska keräysväline ollut paikalla

### ISSUE THREAD

**Issue by LKajan** [punosmobile/jkr-core#6]
Nyt taulussa vain yksi pvm-kenttä.
Vaihda alku, loppu ja näistä generoitu voimassa-daterange-kenttä.

Mieti toteutus vielä tarkemmin. Ajatus tällä hetkellä:
Olemassa olevilla sopimuksilla oletuksena keräysvälineillä alku ja loppu voi olla Null (toistaikseksi), mutta jos uusissa kuljetustiedoissa ei löydy vastaavaa tietoa, niin asetetaan päättymispäiväksi raportointivälin alkupäivämäärä. Jos keräysväline on uusi, niin sitten asetetaan alku raportoinnin alkupäiväksi ja loppu Noneksi.

**Comment by AnniinaMet** [comment]
Sopimukset tulevat nyt kvartaali kerrallaan, joten tämä ei Lahden kannalta olennaista.
