### ISSUE TITLE
Muuta viranomaispäätösten ja jätelajien relaatio N:N

### ISSUE THREAD

**Issue by LKajan** [punosmobile/jkr-core#7]
Nyt yksi viranomaispäätös voi liittyä vain yhteen jätelajiin. Käytännössä yhdellä päätöksellä voidaan kuitenkin vaikuttaa moneen jätelajiin.
Vaihtoehtona on duplikoida päätökset jokaiselle jätelajille.

**Comment by AnniinaMet** [comment]
Ei toistaiseksi ajankohtainen, Todennäköisesti mietitty Tamperetta varten
